test:
  adapter: "<%= ENV["TEST_ADAPTER"] || "postgresql" %>"
  database: "<%= ENV["TEST_DATABASE"] || "sequel_rails_test" %>"
  host: "<%= ENV["TEST_DATABASE_HOST"] %>"
  <% if ENV['TEST_ADAPTER'] != 'sqlite3' %>
  owner: "<%= ENV["TEST_OWNER"] || ENV["USER"] %>"
  user: "<%= ENV["TEST_USERNAME"] || ENV["USER"] %>"
  password: "<%= ENV["TEST_PASSWORD"] %>"
  <% end %>
  <% if ENV['TEST_ADAPTER'] =~ /mysql/ %>
  encoding: "<%= ENV["TEST_ENCODING"] || "utf8" %>"
  <% elsif ENV['TEST_ADAPTER'] =~ /postgres/ %>
  encoding: "<%= ENV["TEST_ENCODING"] || "unicode" %>"
  <% end %>
